# Generated by Django 3.1.5 on 2021-01-31 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WholeIdView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_series_id', models.IntegerField(blank=True, null=True)),
                ('cd_series_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cd_id', models.IntegerField(blank=True, null=True)),
                ('cd_name', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('cd_song_id', models.IntegerField(blank=True, null=True)),
                ('song_id', models.IntegerField(blank=True, null=True)),
                ('song_title', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_everyone', models.BooleanField(blank=True, null=True)),
                ('unit_member_id', models.IntegerField(blank=True, null=True)),
                ('singer_id', models.IntegerField(blank=True, null=True)),
                ('singer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('element_id', models.IntegerField(blank=True, null=True)),
                ('element_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'whole_id_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'cds',
            },
        ),
        migrations.CreateModel(
            name='CdSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cd_series',
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'elements',
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'songs',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_everyone', models.BooleanField()),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='CdExt',
            fields=[
                ('cds_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='million_songs.cds')),
            ],
            bases=('million_songs.cds',),
        ),
        migrations.CreateModel(
            name='CdSeriesExt',
            fields=[
                ('cdseries_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='million_songs.cdseries')),
            ],
            bases=('million_songs.cdseries',),
        ),
        migrations.CreateModel(
            name='SingerExt',
            fields=[
                ('characters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='million_songs.characters')),
            ],
            bases=('million_songs.characters',),
        ),
        migrations.CreateModel(
            name='SongExt',
            fields=[
                ('songs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='million_songs.songs')),
            ],
            bases=('million_songs.songs',),
        ),
        migrations.AddField(
            model_name='characters',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.elements'),
        ),
        migrations.CreateModel(
            name='CdSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.cds')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.songs')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.units')),
            ],
            options={
                'db_table': 'cd_songs',
            },
        ),
        migrations.AddField(
            model_name='cds',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.cdseries'),
        ),
        migrations.CreateModel(
            name='UnitMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.characters')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.units')),
            ],
            options={
                'db_table': 'unit_members',
                'unique_together': {('unit', 'member')},
            },
        ),
    ]
