# Generated by Django 3.1.5 on 2021-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cds',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cdseries',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='characters',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='elements',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cds',
            name='release_date',
            field=models.DateField(default='0001-1-1'),
        ),
        migrations.AddField(
            model_name='songs',
            name='is_everyone_song',
            field=models.BooleanField(default=False),
        ),
    ]
