# Generated by Django 3.1.5 on 2021-01-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0002_auto_20210116_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cds',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.cdseries'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='million_songs.elements'),
        ),
    ]
