# Generated by Django 3.1.5 on 2021-01-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0004_auto_20210116_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='is_everyone_song',
        ),
        migrations.AddField(
            model_name='units',
            name='is_everyone',
            field=models.BooleanField(default=False),
        ),
    ]
