# Generated by Django 3.1.5 on 2021-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0007_auto_20210117_1415'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='units',
            constraint=models.CheckConstraint(check=models.Q(('has_name', True), ('name__in', ({'title': 'Thank You!'},)), _connector='OR'), name='song_name_check'),
        ),
    ]
