# Generated by Django 3.1.5 on 2021-01-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0008_auto_20210117_1456'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='units',
            name='song_name_check',
        ),
    ]
