# Generated by Django 3.1.5 on 2021-01-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0009_auto_20210117_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['song', 'id']},
        ),
        migrations.RemoveField(
            model_name='units',
            name='has_name',
        ),
        migrations.AddField(
            model_name='units',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='million_songs.songs'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='units',
            constraint=models.CheckConstraint(check=models.Q(('name__isnull', True), ('song__isnull', True), _connector='OR'), name='name_or_song_null'),
        ),
    ]
