# Generated by Django 3.1.5 on 2021-01-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million_songs', '0013_auto_20210117_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='million_songs.units'),
        ),
    ]
